version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: express-rate-limit
    versions:
    - 5.2.3
    - 5.2.5
  - dependency-name: helmet
    versions:
    - 4.4.1
  - dependency-name: pg
    versions:
    - 8.5.1
  - dependency-name: express-promise-router
    versions:
    - 4.0.1
